# Server Configuration
server.port=9090

# Email Configuration - USING APP PASSWORD
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aishwaryaraja765@gmail.com
spring.mail.password=ejgbthmrjbtsxqht

# SMTP Properties
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true